config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :tools
    resources :auth_servers

    root to: 'tools#index'
  end

  namespace :api, defaults: { format: 'json' }, constraints: { format: 'json' } do
    namespace :v1 do
      resources :auth_servers, only: [] do
        resources :tools, only: :index
      end
    end
  end

  get '/launch/:tool_client_id', to: 'launches#show', as: :launch
  get '/callback', to: 'launches#callback', as: :launch_callback
  get '/auth', to: 'launches#auth', format: :html
  post '/oauth2/token', to: 'oauth2_tokens#create', format: :json
  resources :keypairs, only: :index, format: :json

  root to: 'admin/tools#index'
end

app/views/fields/launches_field/_show.html.erb
<table>
  <thead>
    <tr>
      <th class="cell-label" scope="col" role="columnheader">Role</th>
      <th class="cell-label" scope="col" role="columnheader">Context</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <tr class="js-table-row">
      <td>Empty</td>
      <td>Empty</td>
      <td><%= link_to('🚀', launch_path(tool_client_id: field.resource.client_id), target: '_blank') %></td>
    </tr>

    <tr class="js-table-row">
      <td>Student</td>
      <td>Empty</td>
      <td><%= link_to('🚀', launch_path(tool_client_id: field.resource.client_id, context: field.student_context), target: '_blank') %></td>
    </tr>

    <tr class="js-table-row">
      <td>Teacher</td>
      <td>Empty</td>
      <td><%= link_to('🚀', launch_path(tool_client_id: field.resource.client_id, context: field.teacher_context), target: '_blank') %></td>
    </tr>
  </tbody>
</table>